{"exception":"NotFoundExc","reason":"Origin with url https://github.com/ContinuumIO/anaconda not found!"}
